// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace H_CommonUI_Tags
{
	HEREWEGO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_ACTION_MAINMENU);

	HEREWEGO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_GAME);
	HEREWEGO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_GAMEMENU);
	HEREWEGO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_MENU);
	HEREWEGO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_MODAL);
}

namespace H_GameplayEvent_Tags
{
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAYEVENT_DEATH);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAYEVENT_RESET);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAYEVENT_REQUESTRESET);

	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ELIMINATION_MESSAGE);
}

namespace H_GameplayEvent_Tags
{
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_BEHAVIOR_SURVIVESDEATH);

}