// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace H_CommonUI_Tags
{
	HEREWEGO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_ACTION_MAINMENU);

	HEREWEGO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_GAME);
	HEREWEGO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_GAMEMENU);
	HEREWEGO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_MENU);
	HEREWEGO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_MODAL);
}

namespace H_GameplayEvent_Tags
{
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAYEVENT_DEATH);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAYEVENT_RESET);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAYEVENT_REQUESTRESET);
}

namespace H_GameplayEvent_Tags
{
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_BEHAVIOR_SURVIVESDEATH);

}

namespace H_Status_Tags
{
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_CROUCHING);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_AUTORUNNING);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_DEATH);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_DEATH_DYING);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_DEATH_DEAD);
}

namespace H_Message_Tags
{
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ELIMINATION_MESSAGE);

	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DAMAGE_MESSAGE);
}

namespace H_SetByCaller_Tags
{
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SETBYCALLER_DAMAGE);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SETBYCALLER_HEAL);
}

namespace H_Damage_Tags
{
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DAMAGE_IMMUNITY);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DAMAGE_SELFDESTRUCT);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DAMAGE_FELLOUTOFWORLD);
}

namespace H_Cheat_Tags
{
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CHEAT_GODMODE);
	HEREWEGO_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CHEAT_UNLIMITEDHEALTH);
}
